### ISSUE TITLE
Importing wso2/googlecalendar

### ISSUE THREAD

**Issue by DinikaSen** [NipunaRanasinghe/package-google-calendar#1]
**Description:**
Import wso2/googlecalendar gives an error stating that package wso2/googlecalendar could not be found. It seems wso2/googlecalendar is not available in Ballerina Central.

**Comment by NipunaRanasinghe** [comment]
It was a typo supposed to be corrected as "nipuna/gcalendar3". Updated the markdown files.

Please try using
```ballerina
import nipuna/gcalendar3; 
```
Thanks!
